sp19:
  season: "spring"
  year: "2019"
  questions:
    - name
    - email
    - phone
    - year
    - applied_before
    - heard_from
    - resume
    - design_portfolio
    - available_for_bp_games
    - why_no_bp_games
    - available_for_retreat
    - why_no_retreat
    - commitments
    - unique_experiences
    - hardest_achievement
    - experience
    - projects
    - service
    - time_commitment_acknowledgement
    - add_to_newsletter

fa19:
  season: "fall"
  year: "2019"
  questions:
    - name
    - email
    - phone
    - year
    - applied_before

    - commitments
    - time_commitment_acknowledgement

    - application_type
    - available_for_bp_games
    - design_portfolio

    - mission_first
    - always_innovate
    - be_humble

    - resume
    - why_no_bp_games
    - available_for_retreat
    - why_no_retreat

    - heard_from
    - add_to_newsletter

sp20:
  season: "spring"
  year: "2020"
  questions:
    - name
    - email
    - phone
    - year
    - applied_before

    - commitments
    - time_commitment_acknowledgement
    - available_for_bp_games
    - available_for_bwbp
    - available_for_meet_the_club

    - mission_first
    - always_innovate
    - be_humble

    - resume
    - why_no_bp_games
    - why_no_bwbp
    - why_no_meet_the_club
    - available_for_retreat
    - why_no_retreat

    - heard_from
    - add_to_newsletter

fa20:
  season: "fall"
  year: "2020"
  questions:
    - name
    - pronouns
    - email
    - phone
    - year
    - applied_before
    - fa20_application_type

    - time_commitment_acknowledgement
    - available_for_bp_games
    - available_for_meet_the_club

    - fa20_mission_first
    - fa20_perpetual_growth
    - fa20_resourcefulness

    - fa20_technical_gauge
    - fa20_classes_additional_info
    - fa20_background_question
    - fa20_project_link

    - why_no_bp_games
    - why_no_meet_the_club

    - fa20_heard_from

sp21:
  season: "spring"
  year: "2021"
  questions:
    - name
    - pronouns
    - sp21_email
    - sp21_phone
    - year
    - sp21_major
    - applied_before
    - sp21_semesters_applied_before
    - sp21_application_type
    - preferred_role

    - time_commitment_acknowledgement
    - sp21_available_for_bp_games
    - sp21_availability_for_meet_the_club

    - sp21_mission_first
    - sp21_perpetual_growth
    - sp21_always_innovate

    - sp21_background_question
    - sp21_project_link

    - sp21_heard_from
    - survey_notice

fa21:
  season: "fall"
  year: "2021"
  questions:
    - name
    - pronouns
    - email
    - phone
    - year
    - major
    - applied_before
    - semesters_applied_before
    - application_type_dev_des_ex
    - preferred_role

    - time_commitment_acknowledgement
    - available_for_bp_games
    - available_for_meet_the_club

    - fa21_mission_first
    - fa21_perpetual_growth
    - fa21_always_innovate

    - background_question

    - heard_from
    - survey_notice

sp22:
  season: "spring"
  year: "2022"
  questions:
    - name
    - pronouns
    - email
    - phone
    - year
    - major
    - applied_before
    - semesters_applied_before
    - application_type

    - sp22_available_for_bp_games
    - sp22_designer_question
    - sp22_external_role_question
    - sp22_external_experience_question

    - time_commitment_acknowledgement

    - sp22_mission_first
    - sp22_perpetual_growth
    - sp22_always_innovate

    - background_question
    - sp21_project_link

    - heard_from
    - survey_notice

fa22:
  season: "fall"
  year: "2022"
  questions:
    - name
    - pronouns
    - email
    - phone
    - year
    - major
    - applied_before
    - semesters_applied_before
    - application_type_dev_des_ex
    - preferred_role

    - fa22_available_for_bp_games
    - fa22_external_experience_question

    - time_commitment_acknowledgement

    - fa22_mission_first
    - fa22_perpetual_growth
    - fa22_always_innovate

    - background_question
    - fa22_project_link

    - heard_from
    - survey_notice

sp23:
  season: "spring"
  year: "2023"
  questions:
    - name
    - pronouns
    - email
    - phone
    - year
    - major
    - applied_before
    - semesters_applied_before
    - application_type_dev_des_ex
    - preferred_role

    - sp23_available_for_bp_games
    - sp23_external_role_question
    - sp23_external_experience_question

    - sp23_mission_first
    - sp23_perpetual_growth
    - sp23_always_innovate

    - background_question
    - sp23_project_link

    - time_commitment_acknowledgement
    - heard_from
    - survey_notice

fa23:
  season: "fall"
  year: "2023"
  questions:
    - name
    - pronouns
    - email
    - phone
    - year
    - major
    - applied_before
    - semesters_applied_before
    - application_type_dev_des_ex
    - preferred_role

    - fa23_available_for_bp_games
    - fa23_external_role_question
    - fa23_external_experience_question
    - fa23_designer_question

    - fa23_mission_first
    - fa23_perpetual_growth
    - fa23_always_innovate

    - fa23_background_question
    - fa23_project_link

    - time_commitment_acknowledgement
    - heard_from
    - survey_notice

