sp19:
  season: 'spring'
  year: '2019'
  questions:
    - name
    - email
    - phone
    - year
    - applied_before
    - heard_from
    - resume
    - design_portfolio
    - available_for_bp_games
    - why_no_bp_games
    - available_for_retreat
    - why_no_retreat
    - commitments
    - unique_experiences
    - hardest_achievement
    - experience
    - projects
    - service
    - time_commitment_acknowledgement
    - add_to_newsletter

fa19:
  season: 'fall'
  year: '2019'
  questions:
    - name
    - email
    - phone
    - year
    - applied_before

    - commitments
    - time_commitment_acknowledgement

    - application_type
    - available_for_bp_games
    - design_portfolio

    - mission_first
    - always_innovate
    - be_humble

    - resume
    - why_no_bp_games
    - available_for_retreat
    - why_no_retreat

    - heard_from
    - add_to_newsletter

sp20:
  season: 'spring'
  year: '2020'
  questions:
    - name
    - email
    - phone
    - year
    - applied_before

    - commitments
    - time_commitment_acknowledgement
    - available_for_bp_games
    - available_for_bwbp
    - available_for_meet_the_club

    - mission_first
    - always_innovate
    - be_humble

    - resume
    - why_no_bp_games
    - why_no_bwbp
    - why_no_meet_the_club
    - available_for_retreat
    - why_no_retreat

    - heard_from
    - add_to_newsletter

fa20:
  season: 'fall'
  year: '2020'
  questions:
    - name
    - pronouns
    - email
    - phone
    - year
    - applied_before
    - fa20_application_type

    - time_commitment_acknowledgement
    - available_for_bp_games
    - available_for_meet_the_club

    - fa20_mission_first
    - fa20_perpetual_growth
    - fa20_resourcefulness

    - fa20_technical_gauge
    - fa20_classes_additional_info
    - fa20_background_question
    - fa20_project_link

    - why_no_bp_games
    - why_no_meet_the_club

    - fa20_heard_from
